language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.in
  - pip install -e .
# command to run tests
script:
  - touch hexy_config.yaml
  - hexy
  - hexy examples -a|sh
